theme: jekyll-theme-slate
title:  When with Rome!
description:  Alexa Rome and the Kingdom of the (not so) Crystal Skulls

author: Alexa L. Rome
email:  alexaleighrome@gmail.com

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts:  true # set to false to remove excerpts on the homepage
